### PR TITLE
Desktop/Mobile  OralHistory/Image

### PR DESCRIPTION
**Pull request by osbaldoAguilar**
Oral-History & Image pages

### CODE REVIEW

**Comment by hifilorau** [comment]
Awesome. Thanks for cleaning this up @osbaldoAguilar .

**Comment by timstallmann** [comment]
Hey @osbaldoAguilar @hifilorau -- a couple of things I'm seeing here that still don't quite look right -- wondering if I'm missing part of the code?

* View tape log / view transcript buttons are styled in correctly
* The page columns don't match what's in the wireframes
* Tags shouldn't be in the same tan box as metadata/citation, they should be outside of it
* On my browser the "More to explore" section is only showing one column of items?
* The font styling for "Oral history" is off

Here's what I'm seeing:

Screen Shot 2020-05-15 at 7 08 06 AM
Screen Shot 2020-05-15 at 7 09 38 AM

**Comment by timstallmann** [comment]
I'm wondering if there's something up with my local dev environment though since that's super-weird.. hrmm.

**Comment by timstallmann** [comment]
Mostly looking good! Added a few clean-up commits; also still seeing a few minor things that I'm wondering if you could fix @osbaldoAguilar @hifilorau ?

* Type styling for the title section doesn't quite match wireframes
Screen Shot 2020-05-15 at 9 00 06 AM


* The container that holds the audio player and the buttons seems to be a fixed width with  overflow cut off, so on some screens it cuts off some of the buttons and part of the audio player

Screen Shot 2020-05-15 at 8 59 44 AM

* For some reason, on Desktop the More to Explore grid is only 1 item wide, when it really should be like 3 items? On tablet widths it is properly 2 items

* The more to explore grid on image pages looks off somehow
Screen Shot 2020-05-15 at 9 00 48 AM

* The containers for tags & item meta are getting put into the same column as the detailed description -- these should be full-width rows each

Screen Shot 2020-05-15 at 8 59 49 AM

**Comment by timstallmann** [comment]
@osbaldoAguilar @hifilorau any chance y'all can address these lingering to-dos so we can finish this item?

**Comment by timstallmann** [comment]
@osbaldoAguilar I'm still seeing the audio player container buttons get cut off on some screen widths -- is that fixed on your end? If so maybe something's up with my local dev machine?

**Pull request merged**
